# Generated by Django 4.2.24 on 2026-09-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='greeting',
            field=models.TextField(blank=True, help_text='Açılış karşılama cümlesi (sesli asistanın ilk söylediği metin).'),
        ),
        migrations.AddField(
            model_name='agent',
            name='instructions',
            field=models.TextField(blank=True, help_text='Ajan davranış kuralları / sistem talimatları.'),
        ),
        migrations.AddField(
            model_name='agent',
            name='speaking_style',
            field=models.CharField(blank=True, default='Sıcak ve profesyonel', max_length=80),
        ),
        migrations.AddField(
            model_name='agent',
            name='tools_enabled',
            field=models.JSONField(blank=True, default=list, help_text='Aktif araçlar: knowledge, transfer, appointment, whatsapp, price_lookup'),
        ),
        migrations.AddField(
            model_name='agent',
            name='voice_label',
            field=models.CharField(blank=True, default='Türkçe · Doğal', max_length=80),
        ),
        migrations.AddField(
            model_name='agent',
            name='voice_sample',
            field=models.FileField(blank=True, null=True, upload_to='voice_samples/'),
        ),
    ]
