# Generated by Django 4.2.24 on 2026-09-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_greeting_agent_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='last_sync_ok',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
