# Generated by Django 4.2.24 on 2026-09-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=16)),
                ('status', models.CharField(choices=[('live', 'Live'), ('ended', 'Ended'), ('missed', 'Missed'), ('failed', 'Failed')], default='ended', max_length=16)),
                ('outcome', models.CharField(choices=[('appointment', 'Appointment created'), ('information', 'Information provided'), ('handoff', 'Handed to team'), ('follow_up', 'Follow-up needed'), ('missed', 'Missed'), ('in_progress', 'In progress')], default='information', max_length=20)),
                ('caller_name', models.CharField(blank=True, max_length=120)),
                ('caller_number', models.CharField(max_length=32)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('detected_need', models.CharField(blank=True, max_length=200)),
                ('action_taken', models.CharField(blank=True, max_length=200)),
                ('recording_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='agents.agent')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.organization')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('agent', 'Agent'), ('caller', 'Caller')], max_length=16)),
                ('text', models.TextField()),
                ('started_offset_seconds', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='conversations.conversation')),
            ],
            options={
                'ordering': ['started_offset_seconds', 'id'],
            },
        ),
    ]
